[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
nft_staking_program = "862wU3Nyrf4H3mxo514hrqvgDhRL7DVfUaCpHbifUYUi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/yow/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
